-- DB 덤프 파일: PostgreSQL 기반 스키마 전용(schema-only) 덤프 파일입니다.
-- 적용 전 PostgreSQL 환경이 준비되어 있어야 합니다.
--
-- PostgreSQL database dump
--

\restrict JYp1gqon9z8g0FqtmNkUrXFM8e5aY6dEjemh2D3lJruzCZojqrgbv6aAYMQrd3m

-- Dumped from database version 16.13 (Debian 16.13-1.pgdg13+1)
-- Dumped by pg_dump version 16.13 (Debian 16.13-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: agent_tasks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agent_tasks (
    id bigint NOT NULL,
    agent_id bigint NOT NULL,
    project_id bigint NOT NULL,
    scan_id bigint NOT NULL,
    finding_id bigint,
    task_type character varying(30) NOT NULL,
    task_status character varying(20) NOT NULL,
    payload_json jsonb,
    queued_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    sent_at timestamp without time zone,
    acked_at timestamp without time zone,
    started_at timestamp without time zone,
    completed_at timestamp without time zone,
    failure_reason text,
    CONSTRAINT chk_agent_tasks_task_status CHECK (((task_status)::text = ANY ((ARRAY['PENDING'::character varying, 'SENT'::character varying, 'ACKED'::character varying, 'RUNNING'::character varying, 'SUCCEEDED'::character varying, 'FAILED'::character varying, 'CANCELED'::character varying])::text[]))),
    CONSTRAINT chk_agent_tasks_task_type CHECK (((task_type)::text = ANY ((ARRAY['SCAN_REQUEST'::character varying, 'PATCH_APPLY'::character varying])::text[])))
);


--
-- Name: agent_tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.agent_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agent_tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: agents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agents (
    id bigint NOT NULL,
    project_id bigint NOT NULL,
    status character varying(20) DEFAULT 'OFFLINE'::character varying NOT NULL,
    last_seen_at timestamp without time zone,
    last_error_message text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    connected_at timestamp without time zone,
    disconnected_at timestamp without time zone,
    auth_token_hash character varying(64),
    is_placeholder boolean DEFAULT false NOT NULL,
    CONSTRAINT chk_agents_status CHECK (((status)::text = ANY ((ARRAY['ONLINE'::character varying, 'OFFLINE'::character varying, 'ERROR'::character varying])::text[])))
);


--
-- Name: agents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.agents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


--
-- Name: projects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projects (
    id bigint NOT NULL,
    user_id bigint,
    guest_owner_key_hash character varying(255),
    name character varying(255) NOT NULL,
    description text,
    default_scan_mode character varying(20) DEFAULT 'AGENT'::character varying NOT NULL,
    default_rule_set_id bigint,
    monitor_enabled boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp without time zone
);


--
-- Name: projects_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.projects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: projects_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.projects_id_seq OWNED BY public.projects.id;


--
-- Name: scan_findings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scan_findings (
    id bigint NOT NULL,
    scan_id bigint NOT NULL,
    scan_nodes_id bigint NOT NULL,
    source_type character varying(20) DEFAULT 'TRIVY'::character varying NOT NULL,
    fingerprint character varying(255) NOT NULL,
    severity character varying(20) NOT NULL,
    category character varying(100) NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    file_path character varying(500),
    resource_name character varying(255),
    rule_code character varying(100),
    attack_scenario text,
    remediation_guide text,
    raw_snippet_json jsonb,
    resolution_status character varying(20) DEFAULT 'OPEN'::character varying NOT NULL,
    patch_approved_by_user_id bigint,
    patch_approved_at timestamp without time zone,
    patch_result_message text,
    backup_file_name character varying(255),
    backup_file_path character varying(500),
    backup_metadata_json jsonb,
    patched_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL,
    line_number integer,
    patch_payload_json jsonb,
    patch_approved_actor_type character varying(20),
    patch_approved_by_guest_owner_key_hash character varying(255),
    resolution_status_source character varying(20),
    resolution_status_changed_at timestamp without time zone,
    resolution_status_changed_actor_type character varying(20),
    resolution_status_changed_by_user_id bigint,
    resolution_status_changed_by_guest_owner_key_hash character varying(255),
    CONSTRAINT chk_scan_findings_resolution_status CHECK (((resolution_status)::text = ANY ((ARRAY['OPEN'::character varying, 'IN_PROGRESS'::character varying, 'RESOLVED'::character varying, 'IGNORED'::character varying])::text[]))),
    CONSTRAINT chk_scan_findings_resolution_status_changed_actor_type CHECK (((resolution_status_changed_actor_type IS NULL) OR ((resolution_status_changed_actor_type)::text = ANY ((ARRAY['USER'::character varying, 'GUEST'::character varying, 'SYSTEM'::character varying])::text[])))),
    CONSTRAINT chk_scan_findings_resolution_status_source CHECK (((resolution_status_source IS NULL) OR ((resolution_status_source)::text = ANY ((ARRAY['MANUAL'::character varying, 'PATCH'::character varying])::text[])))),
    CONSTRAINT chk_scan_findings_severity CHECK (((severity)::text = ANY ((ARRAY['CRITICAL'::character varying, 'HIGH'::character varying, 'MEDIUM'::character varying, 'LOW'::character varying, 'INFO'::character varying])::text[]))),
    CONSTRAINT chk_scan_findings_source_type CHECK (((source_type)::text = ANY ((ARRAY['TRIVY'::character varying, 'CUSTOM_RULE'::character varying, 'AI'::character varying, 'SERVER_AUDIT'::character varying])::text[])))
);


--
-- Name: scan_findings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.scan_findings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scan_findings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: scan_nodes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scan_nodes (
    id bigint NOT NULL,
    scan_id bigint NOT NULL,
    node_key character varying(255) NOT NULL,
    node_name character varying(255),
    node_type character varying(100),
    metadata_json jsonb,
    created_at timestamp without time zone NOT NULL
);


--
-- Name: scan_nodes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.scan_nodes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scan_nodes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: scans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scans (
    id bigint NOT NULL,
    project_id bigint NOT NULL,
    requested_by_user_id bigint,
    request_actor_type character varying(20) DEFAULT 'USER'::character varying NOT NULL,
    agent_id bigint,
    custom_rule_set_id bigint,
    parent_scan_id bigint,
    scan_mode character varying(20) NOT NULL,
    status character varying(20) DEFAULT 'REQUESTED'::character varying NOT NULL,
    progress_step character varying(100),
    failure_reason text,
    target_snapshot_json jsonb,
    raw_result_json jsonb,
    raw_result_path character varying(500),
    requested_at timestamp without time zone NOT NULL,
    started_at timestamp without time zone,
    completed_at timestamp without time zone,
    last_updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    external_scan_id character varying(100),
    analysis_result_path character varying(500),
    deleted_at timestamp without time zone,
    scan_type character varying(30) DEFAULT 'PROJECT_FILE'::character varying NOT NULL,
    CONSTRAINT chk_scans_request_actor_type CHECK (((request_actor_type)::text = ANY ((ARRAY['USER'::character varying, 'GUEST'::character varying, 'SYSTEM'::character varying])::text[]))),
    CONSTRAINT chk_scans_scan_mode CHECK (((scan_mode)::text = ANY ((ARRAY['UPLOAD'::character varying, 'AGENT'::character varying])::text[]))),
    CONSTRAINT chk_scans_scan_type CHECK (((scan_type)::text = ANY ((ARRAY['PROJECT_FILE'::character varying, 'SERVER_AUDIT'::character varying])::text[]))),
    CONSTRAINT chk_scans_status CHECK (((status)::text = ANY ((ARRAY['REQUESTED'::character varying, 'QUEUED'::character varying, 'RUNNING'::character varying, 'RAW_UPLOADED'::character varying, 'DONE'::character varying, 'FAILED'::character varying, 'CANCELED'::character varying])::text[])))
);


--
-- Name: scans_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.scans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_social_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_social_accounts (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    provider character varying(20) NOT NULL,
    provider_user_id character varying(255) NOT NULL,
    social_email character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_user_social_accounts_provider CHECK (((provider)::text = ANY ((ARRAY['GOOGLE'::character varying, 'GITHUB'::character varying])::text[])))
);


--
-- Name: user_social_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_social_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_social_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    display_name character varying(100) NOT NULL,
    password_hash character varying(255),
    account_status character varying(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    token_invalidated_at timestamp without time zone,
    CONSTRAINT chk_users_account_status CHECK (((account_status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'SUSPENDED'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: worker_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.worker_jobs (
    id bigint NOT NULL,
    project_id bigint NOT NULL,
    scan_id bigint NOT NULL,
    job_type character varying(40) NOT NULL,
    job_status character varying(20) NOT NULL,
    payload_json jsonb,
    queued_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    published_at timestamp without time zone,
    started_at timestamp without time zone,
    completed_at timestamp without time zone,
    failure_reason text,
    publish_attempt_count integer DEFAULT 0 NOT NULL,
    last_publish_attempt_at timestamp without time zone,
    CONSTRAINT chk_worker_jobs_job_status CHECK (((job_status)::text = ANY ((ARRAY['PENDING'::character varying, 'PUBLISHED'::character varying, 'RUNNING'::character varying, 'SUCCEEDED'::character varying, 'FAILED'::character varying, 'CANCELED'::character varying])::text[]))),
    CONSTRAINT chk_worker_jobs_job_type CHECK (((job_type)::text = 'UPLOAD_ANALYSIS_REQUEST'::text))
);


--
-- Name: worker_jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.worker_jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.worker_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects ALTER COLUMN id SET DEFAULT nextval('public.projects_id_seq'::regclass);


--
-- Name: agent_tasks agent_tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_tasks
    ADD CONSTRAINT agent_tasks_pkey PRIMARY KEY (id);


--
-- Name: agents agents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agents
    ADD CONSTRAINT agents_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);


--
-- Name: scan_findings scan_findings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scan_findings
    ADD CONSTRAINT scan_findings_pkey PRIMARY KEY (id);


--
-- Name: scan_nodes scan_nodes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scan_nodes
    ADD CONSTRAINT scan_nodes_pkey PRIMARY KEY (id);


--
-- Name: scans scans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scans
    ADD CONSTRAINT scans_pkey PRIMARY KEY (id);


--
-- Name: agents uk_agents_project_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agents
    ADD CONSTRAINT uk_agents_project_id UNIQUE (project_id);


--
-- Name: user_social_accounts user_social_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_social_accounts
    ADD CONSTRAINT user_social_accounts_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: worker_jobs worker_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.worker_jobs
    ADD CONSTRAINT worker_jobs_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: idx_agent_tasks_agent_id_task_status_queued_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agent_tasks_agent_id_task_status_queued_at ON public.agent_tasks USING btree (agent_id, task_status, queued_at);


--
-- Name: idx_agent_tasks_project_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agent_tasks_project_id ON public.agent_tasks USING btree (project_id);


--
-- Name: idx_agents_project_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agents_project_id ON public.agents USING btree (project_id);


--
-- Name: idx_projects_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_projects_created_at ON public.projects USING btree (created_at DESC);


--
-- Name: idx_projects_guest_owner_key_hash_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_projects_guest_owner_key_hash_deleted_at ON public.projects USING btree (guest_owner_key_hash, deleted_at);


--
-- Name: idx_projects_user_id_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_projects_user_id_deleted_at ON public.projects USING btree (user_id, deleted_at);


--
-- Name: idx_scan_findings_scan_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scan_findings_scan_id ON public.scan_findings USING btree (scan_id);


--
-- Name: idx_scan_findings_scan_id_category; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scan_findings_scan_id_category ON public.scan_findings USING btree (scan_id, category);


--
-- Name: idx_scan_findings_scan_id_node_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scan_findings_scan_id_node_id ON public.scan_findings USING btree (scan_id, scan_nodes_id);


--
-- Name: idx_scan_findings_scan_id_resolution_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scan_findings_scan_id_resolution_status ON public.scan_findings USING btree (scan_id, resolution_status);


--
-- Name: idx_scan_findings_scan_id_severity; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scan_findings_scan_id_severity ON public.scan_findings USING btree (scan_id, severity);


--
-- Name: idx_scan_findings_scan_id_source_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scan_findings_scan_id_source_type ON public.scan_findings USING btree (scan_id, source_type);


--
-- Name: idx_scans_external_scan_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scans_external_scan_id ON public.scans USING btree (external_scan_id);


--
-- Name: idx_scans_project_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scans_project_id ON public.scans USING btree (project_id);


--
-- Name: idx_scans_project_id_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scans_project_id_deleted_at ON public.scans USING btree (project_id, deleted_at);


--
-- Name: idx_scans_requested_by_user_id_deleted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scans_requested_by_user_id_deleted_at ON public.scans USING btree (requested_by_user_id, deleted_at);


--
-- Name: idx_scans_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scans_status ON public.scans USING btree (status);


--
-- Name: idx_worker_jobs_job_status_queued_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_worker_jobs_job_status_queued_at ON public.worker_jobs USING btree (job_status, queued_at);


--
-- Name: idx_worker_jobs_project_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_worker_jobs_project_id ON public.worker_jobs USING btree (project_id);


--
-- Name: idx_worker_jobs_scan_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_worker_jobs_scan_id ON public.worker_jobs USING btree (scan_id);


--
-- Name: idx_worker_jobs_status_last_publish_attempt; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_worker_jobs_status_last_publish_attempt ON public.worker_jobs USING btree (job_status, last_publish_attempt_at);


--
-- Name: uk_projects_guest_normalized_name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_projects_guest_normalized_name ON public.projects USING btree (guest_owner_key_hash, lower(regexp_replace(TRIM(BOTH FROM name), '[[:space:]]+'::text, ' '::text, 'g'::text))) WHERE ((deleted_at IS NULL) AND (guest_owner_key_hash IS NOT NULL));


--
-- Name: uk_projects_member_normalized_name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_projects_member_normalized_name ON public.projects USING btree (user_id, lower(regexp_replace(TRIM(BOTH FROM name), '[[:space:]]+'::text, ' '::text, 'g'::text))) WHERE ((deleted_at IS NULL) AND (user_id IS NOT NULL));


--
-- Name: uk_scan_findings_scan_id_node_id_fingerprint; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_scan_findings_scan_id_node_id_fingerprint ON public.scan_findings USING btree (scan_id, scan_nodes_id, fingerprint);


--
-- Name: uk_scan_nodes_scan_id_node_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_scan_nodes_scan_id_node_key ON public.scan_nodes USING btree (scan_id, node_key);


--
-- Name: uk_user_social_accounts_provider_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_user_social_accounts_provider_user_id ON public.user_social_accounts USING btree (provider, provider_user_id);


--
-- Name: uk_user_social_accounts_user_provider; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_user_social_accounts_user_provider ON public.user_social_accounts USING btree (user_id, provider);


--
-- Name: uk_users_active_display_name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_users_active_display_name ON public.users USING btree (display_name) WHERE ((account_status)::text = 'ACTIVE'::text);


--
-- Name: uk_users_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_users_email ON public.users USING btree (email);


--
-- Name: uq_agents_auth_token_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_agents_auth_token_hash ON public.agents USING btree (auth_token_hash);


--
-- Name: agent_tasks fk_agent_tasks_agent; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_tasks
    ADD CONSTRAINT fk_agent_tasks_agent FOREIGN KEY (agent_id) REFERENCES public.agents(id) ON DELETE CASCADE;


--
-- Name: agent_tasks fk_agent_tasks_finding; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_tasks
    ADD CONSTRAINT fk_agent_tasks_finding FOREIGN KEY (finding_id) REFERENCES public.scan_findings(id) ON DELETE SET NULL;


--
-- Name: agent_tasks fk_agent_tasks_project; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_tasks
    ADD CONSTRAINT fk_agent_tasks_project FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: agent_tasks fk_agent_tasks_scan; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_tasks
    ADD CONSTRAINT fk_agent_tasks_scan FOREIGN KEY (scan_id) REFERENCES public.scans(id) ON DELETE CASCADE;


--
-- Name: agents fk_agents_project; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agents
    ADD CONSTRAINT fk_agents_project FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: scan_findings fk_scan_findings_scan; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scan_findings
    ADD CONSTRAINT fk_scan_findings_scan FOREIGN KEY (scan_id) REFERENCES public.scans(id) ON DELETE CASCADE;


--
-- Name: scan_findings fk_scan_findings_scan_node; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scan_findings
    ADD CONSTRAINT fk_scan_findings_scan_node FOREIGN KEY (scan_nodes_id) REFERENCES public.scan_nodes(id) ON DELETE CASCADE;


--
-- Name: scan_nodes fk_scan_nodes_scan; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scan_nodes
    ADD CONSTRAINT fk_scan_nodes_scan FOREIGN KEY (scan_id) REFERENCES public.scans(id) ON DELETE CASCADE;


--
-- Name: user_social_accounts fk_user_social_accounts_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_social_accounts
    ADD CONSTRAINT fk_user_social_accounts_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: worker_jobs fk_worker_jobs_project; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.worker_jobs
    ADD CONSTRAINT fk_worker_jobs_project FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: worker_jobs fk_worker_jobs_scan; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.worker_jobs
    ADD CONSTRAINT fk_worker_jobs_scan FOREIGN KEY (scan_id) REFERENCES public.scans(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict JYp1gqon9z8g0FqtmNkUrXFM8e5aY6dEjemh2D3lJruzCZojqrgbv6aAYMQrd3m
