spring.application.name=ssafer

# ??? ??? ? ?? ?? ??????? ????? ??
spring.flyway.out-of-order=true

spring.config.import=optional:file:.env[.properties]

# JWT
JWT_ISSUER=ssafer
JWT_ACCESS_TOKEN_EXPIRES_SECONDS=900
JWT_REFRESH_TOKEN_EXPIRES_SECONDS=1209600

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
