FROM eclipse-temurin:21-jdk AS builder
WORKDIR /workspace

COPY .mvn .mvn
COPY mvnw pom.xml ./
RUN chmod +x ./mvnw
RUN ./mvnw dependency:go-offline -B

COPY src ./src
RUN ./mvnw package -DskipTests -B

FROM eclipse-temurin:21-jre AS runtime
WORKDIR /app

COPY --from=builder /workspace/target/*.jar app.jar
COPY --from=aquasec/trivy:0.67.2 /usr/local/bin/trivy /usr/local/bin/trivy

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
