export const ROUTES = {
  root: '/',
  welcome: '/welcome',
  login: '/login',
  oauthGoogleCallback: '/oauth/google/callback',
  oauthGithubCallback: '/oauth/github/callback',
  dashboard: '/dashboard',
  projects: '/projects',
  projectDetail: '/projects/:projectId',
  scanDetail: '/scans/:scanId',
  resultDetail: '/results/:scanId',
  resultFindingDetail: '/results/:scanId/findings/:findingId',
  history: '/history',
  monitor: '/monitor',
  guide: '/guide',
  settings: '/settings',
  typingGame: '/typing-game',
  guestContinue: '/guest/continue',
} as const;
