CREATE TABLE user_social_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(20) NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    social_email VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_social_accounts_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_user_social_accounts_provider
        CHECK (provider IN ('GOOGLE', 'GITHUB'))
);

CREATE UNIQUE INDEX uk_user_social_accounts_user_provider
    ON user_social_accounts (user_id, provider);

CREATE UNIQUE INDEX uk_user_social_accounts_provider_user_id
    ON user_social_accounts (provider, provider_user_id);
