CREATE TABLE worker_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    scan_id BIGINT NOT NULL,
    job_type VARCHAR(40) NOT NULL,
    job_status VARCHAR(20) NOT NULL,
    payload_json JSONB,
    queued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMP,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    failure_reason TEXT,
    CONSTRAINT chk_worker_jobs_job_type
        CHECK (job_type IN ('UPLOAD_ANALYSIS_REQUEST')),
    CONSTRAINT chk_worker_jobs_job_status
        CHECK (job_status IN ('PENDING', 'PUBLISHED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELED'))
);

ALTER TABLE worker_jobs
    ADD CONSTRAINT fk_worker_jobs_project
        FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;

ALTER TABLE worker_jobs
    ADD CONSTRAINT fk_worker_jobs_scan
        FOREIGN KEY (scan_id) REFERENCES scans (id) ON DELETE CASCADE;

CREATE INDEX idx_worker_jobs_project_id
    ON worker_jobs (project_id);

CREATE INDEX idx_worker_jobs_scan_id
    ON worker_jobs (scan_id);

CREATE INDEX idx_worker_jobs_job_status_queued_at
    ON worker_jobs (job_status, queued_at);
