CREATE TABLE agents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OFFLINE',
    last_seen_at TIMESTAMP,
    last_error_message TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    connected_at TIMESTAMP,
    disconnected_at TIMESTAMP,
    CONSTRAINT chk_agents_status
        CHECK (status IN ('ONLINE', 'OFFLINE', 'ERROR'))
);

CREATE TABLE agent_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    scan_id BIGINT NOT NULL,
    finding_id BIGINT,
    task_type VARCHAR(30) NOT NULL,
    task_status VARCHAR(20) NOT NULL,
    payload_json JSONB,
    queued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at TIMESTAMP,
    acked_at TIMESTAMP,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    failure_reason TEXT,
    CONSTRAINT chk_agent_tasks_task_type
        CHECK (task_type IN ('SCAN_REQUEST', 'PATCH_APPLY')),
    CONSTRAINT chk_agent_tasks_task_status
        CHECK (task_status IN ('PENDING', 'SENT', 'ACKED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELED'))
);

ALTER TABLE agents
    ADD CONSTRAINT fk_agents_project
        FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;

ALTER TABLE agent_tasks
    ADD CONSTRAINT fk_agent_tasks_agent
        FOREIGN KEY (agent_id) REFERENCES agents (id) ON DELETE CASCADE;

ALTER TABLE agent_tasks
    ADD CONSTRAINT fk_agent_tasks_project
        FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE;

ALTER TABLE agent_tasks
    ADD CONSTRAINT fk_agent_tasks_scan
        FOREIGN KEY (scan_id) REFERENCES scans (id) ON DELETE CASCADE;

ALTER TABLE agent_tasks
    ADD CONSTRAINT fk_agent_tasks_finding
        FOREIGN KEY (finding_id) REFERENCES scan_findings (id) ON DELETE SET NULL;

CREATE INDEX idx_agents_project_id
    ON agents (project_id);

CREATE INDEX idx_agent_tasks_agent_id_task_status_queued_at
    ON agent_tasks (agent_id, task_status, queued_at);

CREATE INDEX idx_agent_tasks_project_id
    ON agent_tasks (project_id);
